// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rij62.Data;

#nullable disable

namespace Rij62.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428203642_CategoryImgUrl")]
    partial class CategoryImgUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rij62.Models.LangEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key", "Language")
                        .HasName("pk_language");

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateTimeOffset>("PickupTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_time");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Btw")
                        .HasColumnType("integer")
                        .HasColumnName("btw");

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_key");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_url");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_key");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.OrderItemChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenProductId")
                        .HasColumnType("integer")
                        .HasColumnName("chosen_product_id");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer")
                        .HasColumnName("order_item_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.HasKey("Id")
                        .HasName("pk_order_item_choices");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_item_choices_order_item_id");

                    b.ToTable("order_item_choices", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Btw")
                        .HasColumnType("integer")
                        .HasColumnName("btw");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_key");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_key");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_url");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<int>("RootCategory")
                        .HasColumnType("integer")
                        .HasColumnName("root_category");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.ProductHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("last_price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_histories");

                    b.ToTable("product_histories", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.ProductStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("default_option_id");

                    b.Property<bool>("MultipleChoice")
                        .HasColumnType("boolean")
                        .HasColumnName("multiple_choice");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_key");

                    b.HasKey("Id")
                        .HasName("pk_product_steps");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_steps_product_id");

                    b.ToTable("product_steps", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.ProductStepOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductStepId")
                        .HasColumnType("integer")
                        .HasColumnName("product_step_id");

                    b.HasKey("Id")
                        .HasName("pk_product_step_options");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_step_options_product_id");

                    b.HasIndex("ProductStepId")
                        .HasDatabaseName("ix_product_step_options_product_step_id");

                    b.ToTable("product_step_options", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_screens");

                    b.ToTable("screens", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Rij62.Models.OrderItem", b =>
                {
                    b.HasOne("Rij62.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Rij62.Models.OrderItemChoice", b =>
                {
                    b.HasOne("Rij62.Models.OrderItem", "OrderItem")
                        .WithMany("Choices")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_choices_order_items_order_item_id");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Rij62.Models.ProductStep", b =>
                {
                    b.HasOne("Rij62.Models.Product", "Product")
                        .WithMany("Steps")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_steps_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Rij62.Models.ProductStepOption", b =>
                {
                    b.HasOne("Rij62.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_step_options_products_product_id");

                    b.HasOne("Rij62.Models.ProductStep", "ProductStep")
                        .WithMany("Options")
                        .HasForeignKey("ProductStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_step_options_product_steps_product_step_id");

                    b.Navigation("Product");

                    b.Navigation("ProductStep");
                });

            modelBuilder.Entity("Rij62.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Rij62.Models.OrderItem", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Rij62.Models.Product", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Rij62.Models.ProductStep", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
